export const ARRAY = [
    {
        id:1,
        name:"Question1", 
        level:"Easy"
    },
    {
        id:2,
        name:"Question2", 
        level:"Easy"
    },
    {
        id:3,
        name:"Question3", 
        level:"Medium"
    },
    {
        id:4,
        name:"Question4", 
        level:"Medium"
    },
    {
        id:5,
        name:"Question5", 
        level:"Hard"
    },
    {
        id:6,
        name:"Question6", 
        level:"Hard"
    },
]; 