export const ARRAY = [
    {
        id:1,
        name:"Question1", 
        level:"Easy",
        completed:false,
        site:"Hackerrank",
    },
    {
        id:2,
        name:"Question2", 
        level:"Easy",
        completed:false,
        site:"Hackerrank",
    },
    {
        id:3,
        name:"Question3", 
        level:"Medium",
        completed:false,
        site:"LeetCode",
    },
    {
        id:4,
        name:"Question4", 
        level:"Medium",
        completed:false,
        site:"Codeforces",
    },
    {
        id:5,
        name:"Question5", 
        level:"Hard",
        completed:false,
        site:"Codechef",
    },
    {
        id:6,
        name:"Question6", 
        level:"Hard",
        completed:false,
        site:"Codechef",
    },

]; 
export const RESOURCES=[
    "Addressing1","Addressing2","Addressing3", "Addressing4","Addressing5","Addressing6","Addressing7","Addressing8"
];
export const VIDEOS=[
    {
        id:1,
        name:"Video1",
        url:"xyz"
    },
    {
        id:2,
        name:"Video2",
        url:"yxz"
    },
    {
        id:3,
        name:"Video3",
        url:"xyz"
    },
];